### ISSUE TITLE
ImportError: No module named bulk

### ISSUE THREAD

**Issue by prahladyeri** [BingAds/BingAds-Python-SDK#12]
Following the [Python SDK](https://msdn.microsoft.com/en-US/library/bing-ads-overview-getting-started-python-with-web-services.aspx#installation) link, I installed the `bingads` package using `sudo pip install` on my ubuntu trusty (14.04) LTS machine. However, when I try to import the bingads module, it gives the below error:

```
>>> import bingads
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bingads.py", line 2, in <module>
    from bingads.bulk import *
ImportError: No module named bulk
```

Here is the output of `pip list|grep bingads`:

`bingads (10.4.1)`

**Comment by imfu** [comment]
Hello, could you check if bulk if downloaded successfully? it should be in your python site-packages, like <your python path>/Lib/site-packages/bingads/
I could not re-pro this error, my guess is bulk is missing or some files are missing. Suggest to pip uninstall it and re-install it.

**Comment by prahladyeri** [comment]
@imfu Here is the list of files in my `dist-packages/bingads/bulk` folder. Though I don't  know which ones I might be missing. The `pip` installer didn't complain about any errors, I already tried uninstall and reinstalling, but didn't work.

```
# /usr/local/lib/python2.7/dist-packages/bingads/bulk$

drwxr-sr-x 3 root staff  4096 Jan 28 02:30 .
drwxr-sr-x 7 root staff  4096 Jan 28 02:30 ..
-rw-r--r-- 1 root staff   640 Jan 28 02:30 bulk_operation_progress_info.py
-rw-r--r-- 1 root staff  1266 Jan 28 02:30 bulk_operation_progress_info.pyc
-rw-r--r-- 1 root staff 13661 Jan 28 02:30 bulk_operation.py
-rw-r--r-- 1 root staff 13761 Jan 28 02:30 bulk_operation.pyc
-rw-r--r-- 1 root staff  2183 Jan 28 02:30 bulk_operation_status.py
-rw-r--r-- 1 root staff  3360 Jan 28 02:30 bulk_operation_status.pyc
-rw-r--r-- 1 root staff 15201 Jan 28 02:30 bulk_service_manager.py
-rw-r--r-- 1 root staff 13089 Jan 28 02:30 bulk_service_manager.pyc
-rw-r--r-- 1 root staff 16697 Jan 28 02:30 download_parameters.py
-rw-r--r-- 1 root staff 18982 Jan 28 02:30 download_parameters.pyc
drwxr-sr-x 4 root staff  4096 Jan 28 02:30 entities
-rw-r--r-- 1 root staff   803 Jan 28 02:30 enums.py
-rw-r--r-- 1 root staff   874 Jan 28 02:30 enums.pyc
-rw-r--r-- 1 root staff  2639 Jan 28 02:30 exceptions.py
-rw-r--r-- 1 root staff  4934 Jan 28 02:30 exceptions.pyc
-rw-r--r-- 1 root staff  5400 Jan 28 02:30 file_reader.py
-rw-r--r-- 1 root staff  6595 Jan 28 02:30 file_reader.pyc
-rw-r--r-- 1 root staff  2299 Jan 28 02:30 file_writer.py
-rw-r--r-- 1 root staff  3364 Jan 28 02:30 file_writer.pyc
-rw-r--r-- 1 root staff   429 Jan 28 02:30 __init__.py
-rw-r--r-- 1 root staff   613 Jan 28 02:30 __init__.pyc
-rw-r--r-- 1 root staff 10515 Jan 28 02:30 upload_parameters.py
-rw-r--r-- 1 root staff 12752 Jan 28 02:30 upload_parameters.pyc

```

**Comment by imfu** [comment]
tried on Ubuntu 14.04, could not repro with latest bingads (10.4.3).
@prahladyeri do you still have any problems on this?
Thanks.
