### ISSUE TITLE
SSL Certificate_Verify_Failed Error

### ISSUE THREAD

**Issue by bnornholm** [BingAds/BingAds-Python-SDK#169]
When running bulk_service_manager_demo, I receive the following error:

`HTTPSConnectionPool(host='bingadsappsstorageprod.blob.core.windows.net', port=443): Max retries exceeded with url: /bulkdownloadresultfiles/2020-308-DownloadHierarchy-1512590001411-46c1863c-b9ef-4a3c-8794-e366934a1249.zip?sv=2018-03-28&sr=b&sig=0Jaf2cb8Pfrx3r8gjP0njqguXw9gaV09maPnIMwKUG0%3D&st=2020-11-03T19%3A43%3A15Z&se=2020-11-03T20%3A08%3A15Z&sp=rl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))`

In Auth_helper and in the documentation I can't find where to place verify=False, or if it is even possible.

**Comment by k24mr** [comment]
Hi @bnornholm , I'm having the same issue as well. Runs fine on MacOSx but fails on an old ubuntu machine. I have updated the ca-certs on my machine as well.

**Comment by davedavis** [comment]
Same issue, all our reporting is broken. Ended up reinstalling Ubuntu thinking I had messed something up. 


Here's the stacktrack
```
Traceback (most recent call last):
  File "/home/dave/PycharmProjects/dg-tracker/main.py", line 22, in <module>
    from dg_microsoft import microsoft_ads_campaign_report
  File "/home/dave/PycharmProjects/dg-tracker/dg_microsoft/microsoft_ads_campaign_report.py", line 26, in <module>
    reporting_service_manager = ReportingServiceManager(authorization_data=authorization_data,
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/bingads/v13/reporting/reporting_service_manager.py", line 40, in __init__
    self._service_client = ServiceClient('ReportingService', 13, authorization_data, environment, **suds_options)
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/bingads/service_client.py", line 49, in __init__
    self._soap_client = Client(self.service_url, **suds_options)
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/suds/reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/suds/reader.py", line 74, in open
    d = self.download(url)
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/suds/reader.py", line 92, in download
    fp = self.options.transport.open(Request(url))
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/suds/transport/https.py", line 62, in open
    return HttpTransport.open(self, request)
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/suds/transport/http.py", line 67, in open
    return self.u2open(u2request)
  File "/home/dave/PycharmProjects/dg-tracker/venv/lib/python3.8/site-packages/suds/transport/http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)>
```

**Comment by davedavis** [comment]
@bnornholm Did you figure out a way to bypass verification?

**Comment by davedavis** [comment]
OK, after a lot of heartache, I've solve this. As usual, the solution was painfully simple. 
Certifi uses it's own bundled certificate bundle, so you can use the one from here: https://curl.haxx.se/ca/cacert.pem

Basically, download it (or use your own from the certifi dist directory)
Then, set the env variable (in /etc/envirnoment if you're on Ubuntu like me) for $SSL_CERT_FILE to the one you downloaded:
export SSL_CERT_FILE=/home/yourname/cacert.pem

Worked immediately from main system CLI. I had to uninstall PyCharm and reinstall it for it to pick up the env variable and start working in virtualenvs again.

**Comment by k24mr** [comment]
@davedavis  Sorry for late reply. I tried your suggestion and still keep on getting the same error. The stacktrace is exactly the same as yours. 

Even creating a new virtual environment didn't help and updating the environment variables inside virtual environment. Also tried updating the machine's ca-certs, plus upgrading certifi and also exporting SSL_CERT_FILE.

**Comment by k24mr** [comment]
I replicated our instance on a different server and the same code/library versions run fine. Do you guys know what could have caused it on my server-side for this to happen ? Thanks.

**Comment by qiyang0221** [comment]
Same problem for me. Ran fine on Mac but fail on my server.
I tried as the [post](https://stackoverflow.com/questions/37327368/bypass-ssl-when-im-using-suds-for-consume-web-service) said. Then it said `Duplicate domain "suds.options" found`.
Anyone has a solution now? Thanks!

**Comment by qiyang0221** [comment]
Hello, everyone. I just solve the problem.
Before creating client, you might need add following code.
```
import ssl

def change_ssl_cert():
    try:
        _create_unverified_https_context = ssl._create_unverified_context
    except AttributeError:
        pass
    else:
        ssl._create_default_https_context = _create_unverified_https_context

```
