### ISSUE TITLE
OAuthDesktopMobileAuthCodeGrant needs and client_secret

### ISSUE THREAD

**Issue by Obdam** [BingAds/BingAds-Python-SDK#188]
Hi,

I am trying to build an Apache Airflow hook for Bing Ads, with as goal to get campaign reporting. However, I get this error:

`Traceback (most recent call last)
  File "/home/airflow/gcs/dags/custom_hooks/bing_ads_hook.py", line 98, in authenticate_with_oaut
    self.REFRESH_TOKEN
  File "/opt/python3.6/lib/python3.6/site-packages/bingads/authorization.py", line 488, in request_oauth_tokens_by_refresh_toke
    tenant = self.tenan
  File "/opt/python3.6/lib/python3.6/site-packages/bingads/authorization.py", line 717, in get_access_toke
    raise OAuthTokenRequestException(error_json.get('error'), error_json.get('error_description')
bingads.exceptions.OAuthTokenRequestException: error_code: invalid_client, error_description: AADSTS70002: The provided request must include a 'client_secret' input parameter.
Trace ID: 0c84e245-ead9-4c47-bb54-539396e1ad00
Correlation ID: 02394eb5-154c-4777-8f13-c9cd90e5f0cb
Timestamp: 2021-07-21 14:25:08`

For OAuth authentication, I've use the auth_helper Python example and this [example](https://github.com/airflow-plugins/bing_ads_plugin/blob/master/hooks/bing_ads_client_v11_hook.py). I've refactored the hook to v13.

My current code fot authentication is as follows:

`    @provide_session
    def save_refresh_token(self, oauth, session=None):
        print("this is oauth.refresh_token", oauth.refresh_token)
        ba_conn = session.query(Connection).filter(
            Connection.conn_id == self.conn_id).first()
        ba_conn.extra = json.dumps({"client_id": self.CLIENT_ID,
                                    "client_state": self.CLIENT_STATE,
                                    "account_id": self.ACCOUNT_ID,
                                    "developer_token": self.DEVELOPER_TOKEN,
                                    "refresh_token": oauth.refresh_token})
        session.commit()

    def authenticate(self, authorization_data):
        # You should authenticate for Bing Ads production services with a Microsoft Account, instead of providing the Bing Ads username and password set.
        # Authentication with a Microsoft Account is currently not supported in Sandbox.
        self.authenticate_with_oauth(authorization_data)

    def authenticate_with_oauth(self, authorization_data):

        authentication = OAuthDesktopMobileAuthCodeGrant(
            client_id=self.CLIENT_ID
        )

        # It is recommended that you specify a non guessable 'state' request parameter to help prevent
        # cross site request forgery (CSRF).
        authentication.state = self.CLIENT_STATE

        # Assign this authentication instance to the authorization_data.
        authorization_data.authentication = authentication

        # Register the callback function to automatically save the refresh token anytime it is refreshed.
        # Uncomment this line if you want to store your refresh token. Be sure to save your refresh token securely.
        authorization_data.authentication.token_refreshed_callback = self.save_refresh_token

        try:
            # If we have a refresh token let's refresh it
            if self.REFRESH_TOKEN is not None:
                authorization_data.authentication.request_oauth_tokens_by_refresh_token(
                    self.REFRESH_TOKEN)
            else:
                raise OAuthTokenRequestException(
                    "error getting refresh token", "Refresh token needs to be requested manually.")

        except OAuthTokenRequestException:
            # The user could not be authenticated or the grant is expired.
            # The user must first sign in and if needed grant the client application access to the requested scope.
            raise Exception(
                "Refresh token needs to be requested. Reference Docs.")`

The authorization_date:

`authorization_data = AuthorizationData(
            account_id=self.ACCOUNT_ID,
            customer_id=self.CUSTOMER_ID,
            developer_token=self.DEVELOPER_TOKEN,
            authentication=None,
        )`

According to the Python example, I assumed it does not need an client_secret for authenticating with the refresh_token. Does this something has to do with the MFA change?

**Comment by qitia** [comment]
yes per my understanding, client_secret is not mandatory for OAuthDesktopMobileAuthCodeGrant , even with MFA. Could you please send the manifest file to me for trouble shooting? you could find the manifest from [here](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade) by navigate to your application. There is a Manifest menu in the main menu pane. You could send the manifest directly to my email: qitia@microsoft.com

**Comment by Obdam** [comment]
I just sent you the email with my manifest.

In the mean time, I am using OAuthWebAuthCodeGrant as a work around, which runs without any issue. The Python function is as follows:

`
    def authenticate_with_oauth(self, authorization_data):
        # IMPORTANT: replace the redirection_uri with the URI configured in Azure Portal. Otherwise the OAuth2 flow doesn't work.
        authentication = OAuthWebAuthCodeGrant(
            client_id=self.CLIENT_ID,
            client_secret=self.CLIENT_SECRET,
            redirection_uri="http://localhost/myapp/"
        )
`

**Comment by qitia** [comment]
hi, if your app is registered as web app, you should use OAuthWebAuthCodeGrant .
