### ISSUE TITLE
TargetImpressionShare is not defined

### ISSUE THREAD

**Issue by kamiltiqets** [BingAds/BingAds-Python-SDK#250]
There's a missing type definition in `extensions.py` file, causing the following exception:

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/bingads/v13/internal/bulk/bulk_object.py", line 107, in convert_to_values
    mapping.convert_to_csv(self, row_values)
  File "/home/airflow/.local/lib/python3.7/site-packages/bingads/v13/internal/bulk/mappings.py", line 112, in convert_to_csv
    self.entity_to_csv(entity, row_values)
  File "/home/airflow/.local/lib/python3.7/site-packages/bingads/v13/internal/extensions.py", line 223, in campaign_biddingscheme_to_csv
    entity_biddingscheme_to_csv(bulk_campaign.campaign, row_values)
  File "/home/airflow/.local/lib/python3.7/site-packages/bingads/v13/internal/extensions.py", line 252, in entity_biddingscheme_to_csv
    row_values[_StringTable.TargetImpressionShare] = TargetImpressionShare(entity.BiddingScheme.TargetImpressionShare)
NameError: name 'TargetImpressionShare' is not defined
```

You can easily verify it's a bug by checking this file and line: https://github.com/BingAds/BingAds-Python-SDK/blob/373a586402bf24af7137b7c49321dbc70c859fce/bingads/v13/internal/extensions.py#L252

Type `TargetImpressionShare` is used, but never imported or defined in this file.

**Comment by qitia** [comment]
we will fix it in next release.
